server:
    port: 1200
    servlet:
        context-path: /tasty-town

spring:
    datasource:
        url: jdbc:mysql://localhost/tasty-town
        username: root
        password: Root

upload:
    file:
        dir: images

order:
    delivery:
        fee: 49
    tax :
        rate: 0.1